### ISSUE TITLE
doesn't work for an empty git repo

### ISSUE THREAD

**Issue by zzuzhp** [ansemjo/version.sh#3]
it seems the script doesn't work for an empty git repo.
it reports:
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: bad revision 'HEAD'
version : commit
commit  : unknown

**Comment by ansemjo** [comment]
Do you mean an initialized git repository with no commits?

In an entirely empty directory with no `.git` directory, there is no error. And in the case of an initialized repository with no commits the above error is printed, yes. But the script should still return successfully and the error will be on stderr. If you don't want to see it just pipe it to `/dev/null`:

```
$ cp ../version.sh .
$ git init
$ sh version.sh 2>/dev/null
version : commit
commit  : unknown
$ echo $?
0
```

What you're seeing are the fallback values when version and commit can not be parsed successfully: `commit` and `unknown`. You can customize those by editing `FALLBACK_VERSION` and `FALLBACK_COMMIT` in the script.

In my opinion, this error should be expected on an empty repository because of course there exists no `HEAD` yet.

**Comment by zzuzhp** [comment]
yes, it's an initialized empty repo without any commits.
but HEAD exists
`cat .git/HEAD` 
 yields
`ref:refs/heads/master` 
but, there is no such 'refs/heads/master' a file under .git/ yet.

i just think it better to handle such exceptions in the script to avoid the print of the error messages from git commands.

**Comment by ansemjo** [comment]
Fair enough. What do you mean by "handle" in this case? Should we just silently ignore the error and print default values? The preceding call to `git describe` does exactly that already:

https://github.com/ansemjo/version.sh/blob/3b288e3223db0bd4407ca1e666512ea0c8732fe6/version.sh#L62-L63

I think I would neither want to try and handle every possible way git could fail and attempt to print helpful error messages, nor would I want to fail the script as a whole. Rather, if it is to be used as part of a build system, it should always succeed and just print fallback values.

What would you say?

**Comment by zzuzhp** [comment]
i used to handle all possible git errors and print a more straightforward message(e.g. "empty repo with no commits") or simple ignore them.
